
runAll: create1 create2 create3 load1 load2 load3

create1:
	cd create_example1 && make

create2:
	cd create_example2 && make

create3:
	cd create_example3 && make

load1:
	cd load_example1 && make

load2:
	cd load_example2 && make

load3:
	cd load_example3 && make

clean:
	cd load_example1 && make clean
	cd load_example2 && make clean
	cd load_example3 && make clean
	cd create_example1 && make clean
	cd create_example2 && make clean
	cd create_example3 && make clean
